INDEXING IN ARRAYS

INDEXING 1-D arrays

In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#index starts from 0
arr[4]

4

In [5]:
#slicing array - arrayname[start:end-1]
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [8]:
#updating the values
arr[0:3]=[23,24,24]
arr

array([23, 24, 24,  3,  4,  5,  6,  7,  8,  9, 10])

NOTE: In arrays, any manipulation done on the elements affects the original array, so explicitly copy the orignal array content if required.

In [11]:
arr_new= arr.copy()
arr_new

array([23, 24, 24,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[4:7]=65
arr

array([23, 34, 34, 34, 65, 65, 65,  7,  8,  9, 10])

In [14]:
arr_new

array([23, 24, 24,  3,  4,  5,  6,  7,  8,  9, 10])

INDEXING 2-D Arrays

In [16]:
a_2d= np.array([[2,4,6],[6,9,12],[12,16,20]])
print('2-Dimensional Arrays : \n',a_2d)

2-Dimensional Arrays : 
 [[ 2  4  6]
 [ 6  9 12]
 [12 16 20]]


In [17]:
a_2d[2]

array([12, 16, 20])

In [18]:
a_2d[2,1]

16

In [24]:
# Slicing 2-D Arrays:
print(a_2d[0:2,0:2],'\n')
print(a_2d[1:3,0:2],'\n')
print(a_2d[0:2,1:3],'\n')
print(a_2d[1:3,0:3],'\n')

[[2 4]
 [6 9]] 

[[ 6  9]
 [12 16]] 

[[ 4  6]
 [ 9 12]] 

[[ 6  9 12]
 [12 16 20]] 



In [40]:
a2d=np.zeros((6,6),dtype=int)
a2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [35]:
a_len=a2d.shape[1]
a_len

6

In [42]:
for i in range(a_len):
    a2d[i]=i
a2d

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5]])

In [41]:
for i in range(a_len):
    a2d[i]=1
a2d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [45]:
#assigning a single value to the row indexed 5
a2d[5]=10
a2d

array([[ 0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4],
       [10, 10, 10, 10, 10, 10]])

In [53]:
#retriving random rows- here row indexed at 5 and 3
a2d[[5,3]]


array([[10, 10, 10, 10, 10, 10],
       [ 3,  3,  3,  3,  3,  3]])

ARRAY TRANSPOSITION

In [58]:
#Taking range of numbers from 1 to 20 and reshaping it in 4 x 5 matrix
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
#Matrix Transposition 
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [60]:
#Matrix Multiplication
np.dot(a,a.T)

array([[  55,  130,  205,  280],
       [ 130,  330,  530,  730],
       [ 205,  530,  855, 1180],
       [ 280,  730, 1180, 1630]])

3-Dimemsional Arrays: 
reshape(outerdimension,m,n)

In [64]:
#tanspose of single element matrix and rows of each matrix becomes columns on final transpose

aa= np.arange(1,21).reshape(2,5,2)
aa

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [63]:
aa.T

array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [66]:
aa.transpose(1,0,2) # outerdimension =1 single row, each matrix will be of 2x2 i.e 0x2

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [68]:
new=np.array([[1,2,3]])
new

array([[1, 2, 3]])

In [71]:
new.swapaxes(0,1)

array([[1],
       [2],
       [3]])