Numpy - used to create Arrays.
Creating ARRAYS from Python Lists

In [1]:
import numpy as np
print(np.__version__)

1.21.5


In [5]:
#creating a list and passing it as an array object
list1=[1,2,3,4]
arr1=np.array(list1)
arr1

array([1, 2, 3, 4])

In [9]:
#creating multi-dimensional array
list2=[21,22,23,24]
t_list=[list1,list2]
n_list=np.array(t_list)
print(n_list)

[[ 1  2  3  4]
 [21 22 23 24]]


In [11]:
#shape- dimensions of arrays
n_list.shape

(2, 4)

In [14]:
#creating arrays with lists as arguements
a= np.array([[12,20,30,40],[100,200,300,400]])
print(a)
print("shape : ",a.shape)

[[ 12  20  30  40]
 [100 200 300 400]]
shape :  (2, 4)


In [19]:
#creating arrays zeros and ones
print('2-D :',np.zeros((2,2)))
print('1-D :',np.zeros(4))


2-D : [[0. 0.]
 [0. 0.]]
1-D : [0. 0. 0. 0.]


In [23]:
# datatype
b=np.ones((5,5))
print(b)
print(b.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [39]:
# empty array- all elements are zero
c=np.empty(4)
print('empty array : ', c)
print(c.dtype, '\n')

e= np.empty((2,2),dtype=int)
print(e, "\n ", e.dtype,'\n')

#full array - all same elements
d=np.full((3,3),12)
print('Full Array: \n ', d, '\n', d.dtype)

empty array :  [0. 0. 0. 0.]
float64 

[[0 0]
 [0 0]] 
  int64 

Full Array: 
  [[12 12 12]
 [12 12 12]
 [12 12 12]] 
 int64


EMPTY ARRAY initialises the elements to values either in negative or zeros WHEREAS 
ZERO ARRAYS assigns all elements to zeros

In [45]:
#Identity Matrix - 3 is nxn matrix dimension
i=np.eye(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [47]:
#np.arange(start,stop,step)
r= np.arange(5)
print(r,'\n')
ran=np.arange(3,30,3)
print(ran)

[0 1 2 3 4] 

[ 3  6  9 12 15 18 21 24 27]


ARRAYS AND SCALARS - operations

In [48]:
5/2

2.5

In [51]:
ar=np.array([[1,2,3,4],[8,9,10,11]])
ar

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [58]:
ar*ar 

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [53]:
ar+ar

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [54]:
ar-1

array([[ 0,  1,  2,  3],
       [ 7,  8,  9, 10]])

In [55]:
ar/2

array([[0.5, 1. , 1.5, 2. ],
       [4. , 4.5, 5. , 5.5]])

In [56]:
1/ar

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [57]:
ar**2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])